### ISSUE TITLE
EventEmitterTransport not parsing response either throwing error

### ISSUE THREAD

**Issue by jamesblasco** [open-rpc/client-js#188]
**Describe the bug**
I am trying to use EventEmitterTransport but I can't manage to make it work.

```ts
 this.transport = new rpc.EventEmitterTransport(this, inputUri, outputUri);
 this.client = new rpc.Client(new rpc.RequestManager([this.transport]));
 this.emit(inputUri, '{"jsonrpc":"2.0","result":0,"id":"1"}');

```

This is not working for me, but it is neither throwing an error.
I am not sure how to continue

For the output, I am doing this and it works correctly
```ts
 this.on(outputUri, (data) => {
       let request = JSON.stringify(data);
       console.log(`Request: ${request}`, data);
 });
```

**Comment by shanejonas** [comment]
hey @jamesblasco heres a working example:

```
import { EventEmitter } from "events";
import { RequestManager, EventEmitterTransport, Client } from "@open-rpc/client-js";

const chan1 = "chan1";
const chan2 = "chan2";

const emitter = new EventEmitter();
const transport = new EventEmitterTransport(emitter, chan1, chan2);
const requestManager = new RequestManager([transport]);
const client = new Client(requestManager);

// event emitter server code
emitter.on(chan2, (jsonrpcRequest) => {
  const res = {
    jsonrpc: "2.0",
    result: "potato",
    id: jsonrpcRequest.id,
  };
  emitter.emit(chan1, JSON.stringify(res));
});

const main = async () => {
  const result = await client.request("addition", [2, 2]);
  console.log(result);
}

main().then(() => {
  console.log("DONE");
});

```

**Comment by shanejonas** [comment]
i think its confusing because the input/output channels are swapped and we should file a ticket on it

**Comment by jamesblasco** [comment]
But in your example 
`emitter.emit(chan1, JSON.stringify(res));`
could it be replaced by
`emitter.emit(chan1, '{"jsonrpc":"2.0","result":"potato","id":"${jsonrpcRequest.id}"}');"`
no?

My problem is when trying to emit notifications or responses from the server-side. In my case, server-side is stdin and stdout from a child process in node.js and the response is already parsed

**Comment by shanejonas** [comment]
> I think its confusing because the input/output channels are swapped and we should file a ticket on it
https://github.com/open-rpc/client-js/issues/188#issuecomment-659686611

i pointed out before there is a bug where the input/output channels are swapped so:

`        this.emit(inputUri, data); // nothing happens`

because they are swapped, you are firing the events on the other channel, I just opened a ticket to fix it here: #190 


my example uses `client.request()`

which then calls this:
 
https://github.com/open-rpc/client-js/blob/131a4fcbb1e205c6b21ae599407b6ef5c089c0b0/src/transports/EventEmitterTransport.ts#L30

firing the event on the `reqUri` instead of `resUri`

**Comment by shanejonas** [comment]
@jamesblasco fixed up the event emitter being swapped. i think your example should work now

**Comment by shanejonas** [comment]
working example now:

```
import { EventEmitter } from "events";
import { RequestManager, EventEmitterTransport, Client } from "@open-rpc/client-js";

const chan1 = "chan1";
const chan2 = "chan2";

const emitter = new EventEmitter();
const transport = new EventEmitterTransport(emitter, chan1, chan2);
const requestManager = new RequestManager([transport]);
const client = new Client(requestManager);

// event emitter server code
emitter.on(chan1, (jsonrpcRequest) => {
  const res = {
    jsonrpc: "2.0",
    result: "potato",
    id: jsonrpcRequest.id,
  };
  emitter.emit(chan2, JSON.stringify(res));
});

const main = async () => {
  const result = await client.request("addition", [2, 2]);
  console.log(result);
}

main().then(() => {
  console.log("DONE");
});
```

**Comment by jamesblasco** [comment]
Thank you so much! Now It works great excepts the notifications, I created a new issue about it #194

**Comment by shanejonas** [comment]
@jamesblasco just an FYI the `.request()` interface is changing slightly in `2.0.0` after this PR gets in: https://github.com/open-rpc/client-js/pull/186

**Comment by jamesblasco** [comment]
Thank you for the update!
