### ISSUE TITLE
Add credentials option for fetch in HTTPTransport 

### ISSUE THREAD

**Issue by abiro** [open-rpc/client-js#200]
Hi,

Thanks for the great work on the library! I'd like to make the following feature request and propose an implementation:

I'd like to be able to set the `credentials` option of [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Parameters) in `HTTPTransport`. I've forked this repo to provide the `credentials` option as an argument to the `HTTPTransport` constructor. You can see my implementation [here](https://github.com/abiro/client-js/commit/ababfc83f6ab11afe37512f73f8e0d9847c61c92). I'm wondering if this commit would be welcome as a pull request?

Best,
Agost

**Comment by shanejonas** [comment]
Hi @abiro,

Thanks for reaching out. 

Pull requests are definitely welcome!

Maybe it can be more generic options passed to the constructor: `options: {credentials, headers}` which also helps with this ticket too: https://github.com/open-rpc/inspector/issues/172

**Comment by abiro** [comment]
Hi @shanejonas,

Thanks fro the quick reply. I'll submit a PR in a few days to add `options: {credentials, headers}` to the `HTTPTransport` constructor.
