### ISSUE TITLE
postMessage-based transports leak promises for notifications

### ISSUE THREAD

**Issue by microbit-matt-hillsdon** [open-rpc/client-js#294]
**Describe the bug**

I think the postMessage-based transports leak promises for notifications (as opposed to requests).

They add them to the transport request manager, but unlike the other implementations they don't seem to settle them. [PostMessageIframeTransport](https://github.com/open-rpc/client-js/blob/b2f9d3155895d6ab97dd467f0083b1070afcd927/src/transports/PostMessageIframeTransport.ts#L45) and [PostMessageWindowTransport](https://github.com/open-rpc/client-js/blob/b2f9d3155895d6ab97dd467f0083b1070afcd927/src/transports/PostMessageWindowTransport.ts#L54) have no equivalent to [this call](https://github.com/open-rpc/client-js/blob/b2f9d3155895d6ab97dd467f0083b1070afcd927/src/transports/WebSocketTransport.ts#L39).

If you add debug to TransportRequestManager you can see an ever-growing pendingRequest object.

I hit this writing a Web Worker based transport, initially following the same approach as the other postMessage-based ones.

**To Reproduce**

The HTTP and EventEmitter transports have test cases for notifications that could be repurposed to cover this.

**Expected behavior**

Equivalent behaviour to the other transports.

**Comment by microbit-matt-hillsdon** [comment]
Investigated some more. Calling `settlePendingRequest` resolves the promise but doesn't fix the leak as it doesn't remove from pendingRequest. This is only done in `resolveRes` which doesn't apply to notifications.

**Comment by zcstarr** [comment]
awesome spot, we cleaned this up and just let us know if you hit issues! Thanks for filing this issue 🥳  helps alot!
